/**
 * crudConfig.js
 * Configuración central de los módulos CRUD del frontend (SAE + catálogos).
 *
 * Cada entrada describe una "entidad" que se renderiza con las páginas genéricas
 * `src/pages/gestion/gestionList.js` (listado) y `gestionAdd.js` (formulario).
 *
 * Estructura de una entrada:
 *  - titulo     : texto mostrado en pantalla.
 *  - kind       : 'catalogo' (endpoints /catalogos/:tabla/...) o 'sae' (endpoints /sae/...).
 *  - tabla/recurso: identificador del recurso en la API.
 *  - endpoints  : rutas relativas de la API (se concatenan con roots.engine).
 *  - columns    : [{ header, key, width? }] columnas del listado.
 *  - fields     : [{ name, label, type, required?, source?, get?, boolean? }]
 *       type: 'text' | 'number' | 'date' | 'textarea' | 'select' | 'boolean'
 *       source (solo select): { tipo:'catalogo'|'sae'|'institucion'|'sedes', tabla?, recurso?, label }
 *       get   : clave del registro crudo que contiene el valor actual (para editar). Default = name.
 *       boolean: true -> el valor se convierte a booleano antes de enviar.
 *
 * CONVENCIÓN DE ENCRIPTACIÓN (PK/FK):
 *  - El PK viene siempre en `idregistro` ENCRIPTADO (doble base64) y se reenvía tal cual.
 *  - Las FKs (idgrado, idcurso, ...) vienen CRUDAS en el listado; el formulario las
 *    enmascara con `tool.encriptar()` antes de enviarlas. El backend las `decriptar()`.
 */

const cat = (titulo, tabla, columns, fields) => ({
    titulo,
    kind: 'catalogo',
    tabla,
    endpoints: {
        listar: `/catalogos/${tabla}/listar`,
        registrar: `/catalogos/${tabla}/registrar`,
        actualizar: `/catalogos/${tabla}/actualizar`,
        borrar: `/catalogos/${tabla}/borrar`,
    },
    columns,
    fields,
});

const sae = (titulo, recurso, columns, fields) => ({
    titulo,
    kind: 'sae',
    endpoints: {
        listar: `/sae/${recurso}/listar`,
        registrar: `/sae/${recurso}/registrar`,
        actualizar: `/sae/${recurso}/actualizar`,
        borrar: `/sae/${recurso}/borrar`,
    },
    columns,
    fields,
});

// Entidad de preescolar (endpoints montados en /preescolar).
const pre = (titulo, recurso, columns, fields) => ({
    titulo,
    kind: 'sae',
    endpoints: {
        listar: `/preescolar/${recurso}/listar`,
        registrar: `/preescolar/${recurso}/registrar`,
        actualizar: `/preescolar/${recurso}/actualizar`,
        borrar: `/preescolar/${recurso}/borrar`,
    },
    columns,
    fields,
});

// Atajos de fuentes (select)
const SRC_CAT = (tabla, label) => ({ tipo: 'catalogo', tabla, label });
const SRC_SAE = (recurso, label) => ({ tipo: 'sae', recurso, label });
const SRC_PRE = (recurso, label) => ({ tipo: 'pre', recurso, label });
const SRC_INST = { tipo: 'institucion', label: 'nombre' };
const SRC_SEDE = { tipo: 'sedes', label: 'nombre' };
// Etiqueta compuesta (nombre completo de docente)
const DOCENTE_LABEL = (row) => `${row.apellido1 || ''} ${row.apellido2 || ''} ${row.nombre1 || ''} ${row.nombre2 || ''}`.trim();

export const CRUD = {
    // ================= CATÁLOGOS =================
    grados: cat('Grados', 'grados',
        [{ header: 'CÓDIGO', key: 'cgradcodi', width: '100px' }, { header: 'DESCRIPCIÓN', key: 'cgraddesc' }, { header: 'NIVEL', key: 'cgradnive' }],
        [{ name: 'cgradcodi', label: 'Código', type: 'number' }, { name: 'cgraddesc', label: 'Descripción', type: 'text', required: true }, { name: 'cgradnive', label: 'Nivel', type: 'text' }]),
    jornadas: cat('Jornadas', 'jornadas',
        [{ header: 'DESCRIPCIÓN', key: 'cjorndesc' }],
        [{ name: 'cjorndesc', label: 'Descripción', type: 'text', required: true }]),
    sexos: cat('Sexos', 'sexos',
        [{ header: 'DESCRIPCIÓN', key: 'csexodesc' }],
        [{ name: 'csexodesc', label: 'Descripción', type: 'text', required: true }]),
    parentescos: cat('Parentescos', 'parentescos',
        [{ header: 'DESCRIPCIÓN', key: 'cparedesc' }],
        [{ name: 'cparedesc', label: 'Descripción', type: 'text', required: true }]),
    tiposdocumento: cat('Tipos de documento', 'tiposdocumento',
        [{ header: 'DESCRIPCIÓN', key: 'ctipodocudesc' }],
        [{ name: 'ctipodocudesc', label: 'Descripción', type: 'text', required: true }]),
    tiposnovedad: cat('Tipos de novedad', 'tiposnovedad',
        [{ header: 'DESCRIPCIÓN', key: 'ctiponovedesc' }, { header: 'ABREV.', key: 'ctiponoveabre', width: '100px' }],
        [{ name: 'ctiponovedesc', label: 'Descripción', type: 'text', required: true }, { name: 'ctiponoveabre', label: 'Abreviatura', type: 'text' }]),
    tiposnota: cat('Tipos de nota', 'tiposnota',
        [{ header: 'DESCRIPCIÓN', key: 'ctiponotadesc' }],
        [{ name: 'ctiponotadesc', label: 'Descripción', type: 'text', required: true }]),
    tiposdesempeno: cat('Tipos de desempeño', 'tiposdesempeno',
        [{ header: 'DESCRIPCIÓN', key: 'cdesctipodese' }],
        [{ name: 'cdesctipodese', label: 'Descripción', type: 'text', required: true }]),
    tiposvinculacion: cat('Tipos de vinculación', 'tiposvinculacion',
        [{ header: 'DESCRIPCIÓN', key: 'ctipovincdesc' }],
        [{ name: 'ctipovincdesc', label: 'Descripción', type: 'text', required: true }]),
    tipossangre: cat('Tipos de sangre', 'tipossangre',
        [{ header: 'DESCRIPCIÓN', key: 'ctiposangdesc' }],
        [{ name: 'ctiposangdesc', label: 'Descripción', type: 'text', required: true }]),
    tipossubsidio: cat('Tipos de subsidio', 'tipossubsidio',
        [{ header: 'DESCRIPCIÓN', key: 'ctiposubsdesc' }],
        [{ name: 'ctiposubsdesc', label: 'Descripción', type: 'text', required: true }]),
    cargos: cat('Cargos', 'cargos',
        [{ header: 'DESCRIPCIÓN', key: 'ccargdesc' }],
        [{ name: 'ccargdesc', label: 'Descripción', type: 'text', required: true }]),
    estadoscurso: cat('Estados de curso', 'estadoscurso',
        [{ header: 'DESCRIPCIÓN', key: 'cestacursdesc' }],
        [{ name: 'cestacursdesc', label: 'Descripción', type: 'text', required: true }]),
    estadosgrado: cat('Estados de grado', 'estadosgrado',
        [{ header: 'DESCRIPCIÓN', key: 'cestagraddesc' }],
        [{ name: 'cestagraddesc', label: 'Descripción', type: 'text', required: true }]),
    estadosgenerales: cat('Estados generales', 'estadosgenerales',
        [{ header: 'DESCRIPCIÓN', key: 'cestagenedesc' }],
        [{ name: 'cestagenedesc', label: 'Descripción', type: 'text', required: true }]),
    estratos: cat('Estratos', 'estratos',
        [{ header: 'DESCRIPCIÓN', key: 'cestrdesc' }],
        [{ name: 'cestrdesc', label: 'Descripción', type: 'number', required: true }]),
    sisben: cat('SISBEN', 'sisben',
        [{ header: 'DESCRIPCIÓN', key: 'csisbdesc' }],
        [{ name: 'csisbdesc', label: 'Descripción', type: 'text', required: true }]),
    zonasresidencia: cat('Zonas de residencia', 'zonasresidencia',
        [{ header: 'DESCRIPCIÓN', key: 'czonaresidesc' }],
        [{ name: 'czonaresidesc', label: 'Descripción', type: 'text', required: true }]),
    etnias: cat('Etnias', 'etnias',
        [{ header: 'CÓDIGO', key: 'cetnicodi', width: '100px' }, { header: 'DESCRIPCIÓN', key: 'cetnidesc' }],
        [{ name: 'cetnicodi', label: 'Código', type: 'number' }, { name: 'cetnidesc', label: 'Descripción', type: 'text', required: true }]),
    resguardos: cat('Resguardos', 'resguardos',
        [{ header: 'CÓDIGO', key: 'cresgcodi', width: '120px' }, { header: 'DESCRIPCIÓN', key: 'cresgdesc' }],
        [{ name: 'cresgcodi', label: 'Código', type: 'text' }, { name: 'cresgdesc', label: 'Descripción', type: 'text', required: true }]),
    discapacidades: cat('Discapacidades', 'discapacidades',
        [{ header: 'DESCRIPCIÓN', key: 'cdiscdesc' }],
        [{ name: 'cdiscdesc', label: 'Descripción', type: 'text', required: true }]),
    capacidades: cat('Capacidades extraordinarias', 'capacidades',
        [{ header: 'DESCRIPCIÓN', key: 'ccapadesc' }],
        [{ name: 'ccapadesc', label: 'Descripción', type: 'text', required: true }]),
    conflictos: cat('Tipos de conflicto', 'conflictos',
        [{ header: 'DESCRIPCIÓN', key: 'cconfdesc' }],
        [{ name: 'cconfdesc', label: 'Descripción', type: 'text', required: true }]),
    fuentesrecursos: cat('Fuentes de recursos', 'fuentesrecursos',
        [{ header: 'DESCRIPCIÓN', key: 'cfuenrecudesc' }],
        [{ name: 'cfuenrecudesc', label: 'Descripción', type: 'text', required: true }]),
    caracter: cat('Carácter del colegio', 'caracter',
        [{ header: 'DESCRIPCIÓN', key: 'ccaradesc' }],
        [{ name: 'ccaradesc', label: 'Descripción', type: 'text', required: true }]),
    especialidades: cat('Especialidades', 'especialidades',
        [{ header: 'DESCRIPCIÓN', key: 'cespeinstdesc' }],
        [{ name: 'cespeinstdesc', label: 'Descripción', type: 'text', required: true }]),
    metodosinstitucionales: cat('Métodos institucionales', 'metodosinstitucionales',
        [{ header: 'DESCRIPCIÓN', key: 'cmetoinstdesc' }],
        [{ name: 'cmetoinstdesc', label: 'Descripción', type: 'text', required: true }]),
    escalanacional: cat('Escala nacional', 'escalanacional',
        [{ header: 'DESCRIPCIÓN', key: 'cescanacidesc' }],
        [{ name: 'cescanacidesc', label: 'Descripción', type: 'text', required: true }]),
    escalacualitativa: cat('Escala cualitativa', 'escalacualitativa',
        [{ header: 'DESCRIPCIÓN', key: 'cescacualdesc' }],
        [{ name: 'cescacualdesc', label: 'Descripción', type: 'text', required: true }]),
    empresas: cat('Empresas (EPS/ARS)', 'empresas',
        [{ header: 'NOMBRE', key: 'cemprdesc' }, { header: 'TELÉFONO', key: 'cemprtele' }, { header: 'CONTACTO', key: 'cemprpers' }],
        [{ name: 'cemprdesc', label: 'Nombre', type: 'text', required: true }, { name: 'cemprdire', label: 'Dirección', type: 'text' }, { name: 'cemprtele', label: 'Teléfono', type: 'text' }, { name: 'cemprpers', label: 'Contacto', type: 'text' }]),
    icbf: cat('ICBF', 'icbf',
        [{ header: 'NOMBRE', key: 'cnombicbf' }],
        [{ name: 'cnombicbf', label: 'Nombre', type: 'text', required: true }]),
    departamentos: cat('Departamentos', 'departamentos',
        [{ header: 'DESCRIPCIÓN', key: 'cdepageogdesc' }],
        [{ name: 'cdepageogdesc', label: 'Descripción', type: 'text', required: true }]),
    ciudades: cat('Ciudades / municipios', 'ciudades',
        [{ header: 'MUNICIPIO', key: 'cciuddesc' }],
        [{ name: 'cdepageogid', label: 'Departamento', type: 'select', source: SRC_CAT('departamentos', 'cdepageogdesc'), required: true }, { name: 'cciuddesc', label: 'Municipio', type: 'text', required: true }]),

    // ================= SAE =================
    institucion: sae('Instituciones', 'instituciones/instituciones',
        [{ header: 'NOMBRE', key: 'nombre' }, { header: 'DANE', key: 'codigodane' }, { header: 'NIT', key: 'nit' }, { header: 'TELÉFONO', key: 'telefono' }],
        [{ name: 'nombre', label: 'Nombre', type: 'text', required: true }, { name: 'codigodane', label: 'Código DANE', type: 'text' }, { name: 'nit', label: 'NIT', type: 'text' }, { name: 'direccion', label: 'Dirección', type: 'text' }, { name: 'telefono', label: 'Teléfono', type: 'text' }, { name: 'email', label: 'Email', type: 'text' }, { name: 'lema', label: 'Lema', type: 'text' }, { name: 'idzona', label: 'Zona', type: 'select', source: SRC_CAT('zonasresidencia', 'czonaresidesc') }, { name: 'idcaracter', label: 'Carácter', type: 'select', source: SRC_CAT('caracter', 'ccaradesc') }, { name: 'idespecialidad', label: 'Especialidad', type: 'select', source: SRC_CAT('especialidades', 'cespeinstdesc') }, { name: 'idmetodo', label: 'Método', type: 'select', source: SRC_CAT('metodosinstitucionales', 'cmetoinstdesc') }]),
    sedes: sae('Sedes', 'sedes',
        [{ header: 'NOMBRE', key: 'nombre' }],
        [{ name: 'idinstitucion', label: 'Institución', type: 'select', source: SRC_INST, required: true }, { name: 'nombre', label: 'Nombre', type: 'text', required: true }]),

    anos: sae('Años lectivos', 'anos',
        [{ header: 'DESCRIPCIÓN', key: 'descripcion' }, { header: 'INICIO', key: 'fechainicio' }, { header: 'FIN', key: 'fechafin' }],
        [{ name: 'descripcion', label: 'Descripción', type: 'text', required: true }, { name: 'fechainicio', label: 'Fecha inicio', type: 'date' }, { name: 'fechafin', label: 'Fecha fin', type: 'date' }]),
    periodos: sae('Periodos', 'periodos',
        [{ header: 'NOMBRE', key: 'nombre' }, { header: 'DESCRIPCIÓN', key: 'descripcion' }],
        [{ name: 'nombre', label: 'Nombre', type: 'text', required: true }, { name: 'descripcion', label: 'Descripción', type: 'text' }]),
    anolperi: sae('Periodos institucionales', 'anolperi',
        [{ header: 'PERIODO', key: 'periodo' }, { header: 'DESCRIPCIÓN', key: 'descripcion' }, { header: 'INICIO', key: 'fechainicio' }, { header: 'FIN', key: 'fechafin' }],
        [{ name: 'idinstitucion', label: 'Institución', type: 'select', source: SRC_INST, required: true, get: 'cinstid' }, { name: 'idano', label: 'Año', type: 'select', source: SRC_SAE('anos', 'descripcion'), required: true, get: 'canolid' }, { name: 'idperiodo', label: 'Periodo', type: 'select', source: SRC_SAE('periodos', 'nombre'), required: true, get: 'cperiid' }, { name: 'descripcion', label: 'Descripción', type: 'text' }, { name: 'fechainicio', label: 'Fecha inicio', type: 'date' }, { name: 'fechafin', label: 'Fecha fin', type: 'date' }, { name: 'valor', label: 'Valor (%)', type: 'number' }]),

    escalas: sae('Escalas de calificación', 'escalas',
        [{ header: 'NACIONAL', key: 'escalanacional' }, { header: 'CUALITATIVA', key: 'escalacualitativa' }, { header: 'DESDE', key: 'desde' }, { header: 'HASTA', key: 'hasta' }],
        [{ name: 'idinstitucion', label: 'Institución', type: 'select', source: SRC_INST, required: true }, { name: 'idano', label: 'Año', type: 'select', source: SRC_SAE('anos', 'descripcion'), required: true }, { name: 'idescalanacional', label: 'Escala nacional', type: 'select', source: SRC_CAT('escalanacional', 'cescanacidesc'), required: true }, { name: 'idescalacualitativa', label: 'Escala cualitativa', type: 'select', source: SRC_CAT('escalacualitativa', 'cescacualdesc'), required: true }, { name: 'desde', label: 'Desde', type: 'number' }, { name: 'hasta', label: 'Hasta', type: 'number' }]),
    sie: sae('SIE', 'sie',
        [{ header: 'VALOR PROMOCIÓN', key: 'valorpromocion' }],
        [{ name: 'idinstitucion', label: 'Institución', type: 'select', source: SRC_INST, required: true }, { name: 'idano', label: 'Año', type: 'select', source: SRC_SAE('anos', 'descripcion'), required: true }, { name: 'idtipodesempeno', label: 'Tipo de desempeño', type: 'select', source: SRC_CAT('tiposdesempeno', 'cdesctipodese') }, { name: 'valorpromocion', label: 'Valor de promoción', type: 'number' }]),
    certificados: sae('Certificados / resoluciones', 'certificados',
        [{ header: 'TÍTULO', key: 'titulo' }],
        [{ name: 'idinstitucion', label: 'Institución', type: 'select', source: SRC_INST, required: true }, { name: 'titulo', label: 'Título', type: 'text', required: true }, { name: 'parrafo1', label: 'Párrafo 1', type: 'textarea' }, { name: 'parrafo2', label: 'Párrafo 2', type: 'textarea' }]),
    constancias: sae('Constancias', 'constancias',
        [{ header: 'TÍTULO', key: 'titulo' }],
        [{ name: 'idinstitucion', label: 'Institución', type: 'select', source: SRC_INST, required: true }, { name: 'titulo', label: 'Título', type: 'text', required: true }, { name: 'parrafo1', label: 'Párrafo 1', type: 'textarea' }, { name: 'parrafo2', label: 'Párrafo 2', type: 'textarea' }]),
    pazsalvo: sae('Paz y salvo', 'pazsalvo',
        [{ header: 'TÍTULO', key: 'titulo1' }],
        [{ name: 'idinstitucion', label: 'Institución', type: 'select', source: SRC_INST, required: true }, { name: 'titulo1', label: 'Título 1', type: 'text' }, { name: 'titulo2', label: 'Título 2', type: 'text' }, { name: 'parrafo1', label: 'Párrafo 1', type: 'textarea' }, { name: 'parrafo2', label: 'Párrafo 2', type: 'textarea' }]),
    firmas: sae('Firmas', 'firmas',
        [{ header: 'DOCENTE', key: 'docente' }, { header: 'CARGO', key: 'cargo' }, { header: 'ORDEN', key: 'orden' }],
        [{ name: 'idinstitucion', label: 'Institución', type: 'select', source: SRC_INST, required: true }, { name: 'iddocente', label: 'Docente', type: 'select', source: { tipo: 'sae', recurso: 'docentes', label: DOCENTE_LABEL }, required: true }, { name: 'cargo', label: 'Cargo', type: 'text' }, { name: 'tipo', label: 'Tipo', type: 'number' }, { name: 'orden', label: 'Orden', type: 'number' }]),

    cursos: sae('Cursos', 'cursos',
        [{ header: 'NOMBRE', key: 'nombre' }, { header: 'GRADO', key: 'grado' }, { header: 'JORNADA', key: 'jornada' }, { header: 'AÑO', key: 'ano' }],
        [{ name: 'idinstitucion', label: 'Institución', type: 'select', source: SRC_INST, required: true, get: 'cinstid' }, { name: 'idgrado', label: 'Grado', type: 'select', source: SRC_CAT('grados', 'cgraddesc'), required: true, get: 'cgradid' }, { name: 'idjornada', label: 'Jornada', type: 'select', source: SRC_CAT('jornadas', 'cjorndesc'), get: 'cjornid' }, { name: 'idano', label: 'Año', type: 'select', source: SRC_SAE('anos', 'descripcion'), required: true, get: 'canolid' }, { name: 'nombre', label: 'Nombre', type: 'text', required: true }, { name: 'limiteestudiantes', label: 'Límite de estudiantes', type: 'number' }, { name: 'idsede', label: 'Sede', type: 'select', source: SRC_SEDE }]),

    areas: sae('Áreas del saber', 'areas',
        [{ header: 'DESCRIPCIÓN', key: 'descripcion' }],
        [{ name: 'descripcion', label: 'Descripción', type: 'text', required: true }, { name: 'comentario', label: 'Comentario', type: 'text' }]),
    asignaturas: sae('Asignaturas', 'asignaturas',
        [{ header: 'DESCRIPCIÓN', key: 'descripcion' }, { header: 'ÁREA', key: 'area' }, { header: 'ABREV.', key: 'abreviatura' }],
        [{ name: 'descripcion', label: 'Descripción', type: 'text', required: true }, { name: 'idarea', label: 'Área', type: 'select', source: SRC_SAE('areas', 'descripcion') }, { name: 'abreviatura', label: 'Abreviatura', type: 'text' }, { name: 'evaluable', label: 'Evaluable', type: 'boolean' }]),
    instarea: sae('Áreas por institución', 'instarea',
        [{ header: 'ÁREA', key: 'area' }],
        [{ name: 'idinstitucion', label: 'Institución', type: 'select', source: SRC_INST, required: true }, { name: 'idarea', label: 'Área', type: 'select', source: SRC_SAE('areas', 'descripcion'), required: true }]),
    contenidos: sae('Contenidos programáticos', 'contenidos',
        [{ header: 'CÓDIGO', key: 'codigo' }, { header: 'DESCRIPCIÓN', key: 'descripcion' }, { header: 'ASIGNATURA', key: 'asignatura' }],
        [{ name: 'idasignatura', label: 'Asignatura', type: 'select', source: SRC_SAE('asignaturas', 'descripcion'), required: true }, { name: 'codigo', label: 'Código', type: 'text' }, { name: 'descripcion', label: 'Descripción', type: 'text', required: true }]),
    asigcurscontprog: sae('Contenido por asignación', 'asigcurscontprog',
        [{ header: 'CONTENIDO', key: 'contenido' }],
        [{ name: 'idasigcurs', label: 'Asignación', type: 'select', source: SRC_SAE('asignaciones', 'asignatura'), required: true }, { name: 'idcontenido', label: 'Contenido', type: 'select', source: SRC_SAE('contenidos', 'descripcion'), required: true }, { name: 'fecha', label: 'Fecha', type: 'date' }]),
    areaconf: sae('Configuración de áreas', 'areaconf',
        [{ header: 'ASIGNATURA', key: 'asignatura' }, { header: 'GRADO', key: 'grado' }, { header: 'VALOR', key: 'valor' }],
        [{ name: 'idano', label: 'Año', type: 'select', source: SRC_SAE('anos', 'descripcion'), required: true }, { name: 'idinstitucion', label: 'Institución', type: 'select', source: SRC_INST, required: true }, { name: 'idasignatura', label: 'Asignatura', type: 'select', source: SRC_SAE('asignaturas', 'descripcion'), required: true }, { name: 'idgrado', label: 'Grado', type: 'select', source: SRC_CAT('grados', 'cgraddesc'), required: true }, { name: 'valor', label: 'Valor', type: 'number' }]),

    docentes: sae('Docentes', 'docentes',
        [{ header: 'IDENTIFICACIÓN', key: 'identificacion' }, { header: 'APELLIDOS', key: 'apellido1' }, { header: 'NOMBRES', key: 'nombre1' }, { header: 'EMAIL', key: 'email' }],
        [{ name: 'identificacion', label: 'Identificación', type: 'text', required: true }, { name: 'idtipodocumento', label: 'Tipo documento', type: 'select', source: SRC_CAT('tiposdocumento', 'ctipodocudesc') }, { name: 'nombre1', label: 'Primer nombre', type: 'text' }, { name: 'nombre2', label: 'Segundo nombre', type: 'text' }, { name: 'apellido1', label: 'Primer apellido', type: 'text' }, { name: 'apellido2', label: 'Segundo apellido', type: 'text' }, { name: 'fechanacimiento', label: 'Fecha nacimiento', type: 'date' }, { name: 'idsexo', label: 'Sexo', type: 'select', source: SRC_CAT('sexos', 'csexodesc') }, { name: 'celular', label: 'Celular', type: 'text' }, { name: 'telefono', label: 'Teléfono', type: 'text' }, { name: 'direccion', label: 'Dirección', type: 'text' }, { name: 'email', label: 'Email', type: 'text' }, { name: 'fechaingreso', label: 'Fecha ingreso', type: 'date' }]),
    contrataciones: sae('Contratación de docentes', 'contrataciones',
        [{ header: 'DOCENTE', key: 'docente' }, { header: 'CARGO', key: 'cargo' }],
        [{ name: 'idinstitucion', label: 'Institución', type: 'select', source: SRC_INST, required: true }, { name: 'iddocente', label: 'Docente', type: 'select', source: { tipo: 'sae', recurso: 'docentes', label: DOCENTE_LABEL }, required: true }, { name: 'idano', label: 'Año', type: 'select', source: SRC_SAE('anos', 'descripcion'), required: true }, { name: 'idcargo', label: 'Cargo', type: 'select', source: SRC_CAT('cargos', 'ccargdesc') }, { name: 'idtipovinculacion', label: 'Vinculación', type: 'select', source: SRC_CAT('tiposvinculacion', 'ctipovincdesc') }, { name: 'salario', label: 'Salario', type: 'number' }, { name: 'fechainicio', label: 'Fecha inicio', type: 'date' }, { name: 'fechafin', label: 'Fecha fin', type: 'date' }]),
    asignaciones: sae('Asignación académica', 'asignaciones',
        [{ header: 'ASIGNATURA', key: 'asignatura' }, { header: 'CURSO', key: 'curso' }, { header: 'DOCENTE', key: 'docente' }],
        [{ name: 'idasignatura', label: 'Asignatura', type: 'select', source: SRC_SAE('asignaturas', 'descripcion'), required: true }, { name: 'idcurso', label: 'Curso', type: 'select', source: SRC_SAE('cursos', 'nombre'), required: true }, { name: 'iddocente', label: 'Docente', type: 'select', source: { tipo: 'sae', recurso: 'docentes', label: DOCENTE_LABEL }, required: true }, { name: 'horainicio', label: 'Hora inicio', type: 'text' }, { name: 'horafin', label: 'Hora fin', type: 'text' }, { name: 'duracion', label: 'Duración', type: 'number' }]),

    estudiantes: sae('Estudiantes', 'estudiantes',
        [{ header: 'IDENTIFICACIÓN', key: 'identificacion' }, { header: 'APELLIDOS', key: 'apellido1' }, { header: 'NOMBRES', key: 'nombre1' }],
        [{ name: 'identificacion', label: 'Identificación', type: 'text', required: true }, { name: 'idtipodocumento', label: 'Tipo documento', type: 'select', source: SRC_CAT('tiposdocumento', 'ctipodocudesc') }, { name: 'nombre1', label: 'Primer nombre', type: 'text' }, { name: 'nombre2', label: 'Segundo nombre', type: 'text' }, { name: 'apellido1', label: 'Primer apellido', type: 'text' }, { name: 'apellido2', label: 'Segundo apellido', type: 'text' }, { name: 'fechanacimiento', label: 'Fecha nacimiento', type: 'date' }, { name: 'idgenero', label: 'Género', type: 'select', source: SRC_CAT('sexos', 'csexodesc') }, { name: 'telefono', label: 'Teléfono', type: 'text' }, { name: 'direccion', label: 'Dirección', type: 'text' }, { name: 'email', label: 'Email', type: 'text' }]),
    matriculas: sae('Matrículas', 'matriculas',
        [{ header: 'ESTUDIANTE', key: 'estudiante' }, { header: 'CURSO', key: 'curso' }],
        [{ name: 'idestudiante', label: 'Estudiante', type: 'select', source: { tipo: 'sae', recurso: 'estudiantes', label: (row) => `${row.apellido1 || ''} ${row.nombre1 || ''}`.trim() }, required: true }, { name: 'idcurso', label: 'Curso', type: 'select', source: SRC_SAE('cursos', 'nombre'), required: true }, { name: 'idinstitucion', label: 'Institución', type: 'select', source: SRC_INST, required: true }, { name: 'nuevo', label: 'Estudiante nuevo', type: 'boolean' }, { name: 'repitente', label: 'Repitente', type: 'boolean' }, { name: 'valorinscripcion', label: 'Valor inscripción', type: 'number' }, { name: 'valorpension', label: 'Valor pensión', type: 'number' }, { name: 'descuento', label: 'Descuento', type: 'number' }]),
    acudientes: sae('Acudientes', 'acudientes',
        [{ header: 'IDENTIFICACIÓN', key: 'identificacion' }, { header: 'NOMBRE', key: 'nombre' }, { header: 'TELÉFONO', key: 'telefono' }],
        [{ name: 'idmatricula', label: 'Matrícula', type: 'select', source: SRC_SAE('matriculas', 'estudiante'), required: true }, { name: 'identificacion', label: 'Identificación', type: 'text' }, { name: 'nombre', label: 'Nombre', type: 'text', required: true }, { name: 'telefono', label: 'Teléfono', type: 'text' }, { name: 'direccion', label: 'Dirección', type: 'text' }, { name: 'email', label: 'Email', type: 'text' }, { name: 'idparentesco', label: 'Parentesco', type: 'select', source: SRC_CAT('parentescos', 'cparedesc') }]),
    otrosdatos: sae('Otros datos (anexo 6)', 'otrosdatos',
        [{ header: 'MATRÍCULA', key: 'idmatricula' }],
        [{ name: 'idmatricula', label: 'Matrícula', type: 'select', source: SRC_SAE('matriculas', 'estudiante'), required: true }, { name: 'iddiscapacidad', label: 'Discapacidad', type: 'select', source: SRC_CAT('discapacidades', 'cdiscdesc') }, { name: 'idcapacidad', label: 'Capacidad', type: 'select', source: SRC_CAT('capacidades', 'ccapadesc') }, { name: 'idetnia', label: 'Etnia', type: 'select', source: SRC_CAT('etnias', 'cetnidesc') }, { name: 'idfuenterecursos', label: 'Fuente de recursos', type: 'select', source: SRC_CAT('fuentesrecursos', 'cfuenrecudesc') }]),
    socioeconomicos: sae('Datos socioeconómicos', 'socioeconomicos',
        [{ header: 'MATRÍCULA', key: 'idmatricula' }],
        [{ name: 'idmatricula', label: 'Matrícula', type: 'select', source: SRC_SAE('matriculas', 'estudiante'), required: true }, { name: 'idzonaresidencia', label: 'Zona de residencia', type: 'select', source: SRC_CAT('zonasresidencia', 'czonaresidesc') }, { name: 'idestrato', label: 'Estrato', type: 'select', source: SRC_CAT('estratos', 'cestrdesc') }, { name: 'idsisben', label: 'SISBEN', type: 'select', source: SRC_CAT('sisben', 'csisbdesc') }, { name: 'iddepartamento', label: 'Departamento', type: 'select', source: SRC_CAT('departamentos', 'cdepageogdesc') }, { name: 'idmunicipio', label: 'Municipio', type: 'select', source: SRC_CAT('ciudades', 'cciuddesc') }]),
    pagos: sae('Pagos de matrícula', 'pagos',
        [{ header: 'PERIODO', key: 'periodo' }, { header: 'FECHA', key: 'fecha' }],
        [{ name: 'idmatricula', label: 'Matrícula', type: 'select', source: SRC_SAE('matriculas', 'estudiante'), required: true }, { name: 'periodo', label: 'Periodo', type: 'number', required: true }, { name: 'fecha', label: 'Fecha', type: 'date' }]),

    competencias: sae('Indicadores de desempeño', 'competencias',
        [{ header: 'CÓDIGO', key: 'codigo' }, { header: 'DESCRIPCIÓN', key: 'descripcion' }, { header: 'ÁREA', key: 'area' }],
        [{ name: 'idarea', label: 'Área', type: 'select', source: SRC_SAE('areas', 'descripcion'), required: true }, { name: 'idgrado', label: 'Grado', type: 'text' }, { name: 'codigo', label: 'Código', type: 'text' }, { name: 'descripcion', label: 'Descripción', type: 'text', required: true }, { name: 'idasignatura', label: 'Asignatura', type: 'select', source: SRC_SAE('asignaturas', 'descripcion') }, { name: 'observacion', label: 'Observación', type: 'textarea' }]),
    asigcurscomp: sae('Competencias por asignación', 'asigcurscomp',
        [{ header: 'COMPETENCIA', key: 'competencia' }],
        [{ name: 'idasigcurs', label: 'Asignación', type: 'select', source: SRC_SAE('asignaciones', 'asignatura'), required: true }, { name: 'idcompetencia', label: 'Competencia', type: 'select', source: SRC_SAE('competencias', 'descripcion'), required: true }]),

    notas: sae('Calificaciones', 'notas',
        [{ header: 'ESTUDIANTE', key: 'estudiante' }, { header: 'COMPETENCIA', key: 'competencia' }, { header: 'VALOR', key: 'valor' }],
        [{ name: 'idasigcurs', label: 'Asignación', type: 'select', source: SRC_SAE('asignaciones', 'asignatura'), required: true }, { name: 'idcompetencia', label: 'Competencia', type: 'select', source: SRC_SAE('competencias', 'descripcion'), required: true }, { name: 'idperiodo', label: 'Periodo', type: 'select', source: SRC_SAE('anolperi', 'descripcion') }, { name: 'idmatricula', label: 'Matrícula', type: 'select', source: SRC_SAE('matriculas', 'estudiante'), required: true }, { name: 'valor', label: 'Valor', type: 'number', required: true }, { name: 'fecha', label: 'Fecha', type: 'date' }, { name: 'observacion', label: 'Observación', type: 'textarea' }]),
    definitivas: sae('Definitivas', 'definitivas',
        [{ header: 'VALOR', key: 'valor' }, { header: 'DESEMPEÑO', key: 'desempeno' }],
        [{ name: 'idmatricula', label: 'Matrícula', type: 'select', source: SRC_SAE('matriculas', 'estudiante'), required: true }, { name: 'idasigcurs', label: 'Asignación', type: 'select', source: SRC_SAE('asignaciones', 'asignatura'), required: true }, { name: 'idperiodo', label: 'Periodo', type: 'select', source: SRC_SAE('anolperi', 'descripcion') }, { name: 'idtipodesempeno', label: 'Tipo desempeño', type: 'select', source: SRC_CAT('tiposdesempeno', 'cdesctipodese') }, { name: 'valor', label: 'Valor', type: 'number', required: true }, { name: 'observacion', label: 'Observación', type: 'textarea' }]),
    promediosdef: sae('Promedios definitivos', 'promediosdef',
        [{ header: 'VALOR', key: 'valor' }],
        [{ name: 'idmatricula', label: 'Matrícula', type: 'select', source: SRC_SAE('matriculas', 'estudiante'), required: true }, { name: 'idperiodo', label: 'Periodo', type: 'select', source: SRC_SAE('anolperi', 'descripcion') }, { name: 'idtipopromedio', label: 'Tipo promedio', type: 'number' }, { name: 'valor', label: 'Valor', type: 'number', required: true }]),
    promediosasig: sae('Promedios por asignatura', 'promediosasig',
        [{ header: 'PROMEDIO', key: 'promedio' }, { header: 'PONDERACIÓN', key: 'ponderacion' }],
        [{ name: 'idpromedio', label: 'Promedio', type: 'select', source: SRC_SAE('promedios', 'promediofinal'), required: true }, { name: 'idano', label: 'Año', type: 'select', source: SRC_SAE('anos', 'descripcion'), required: true }, { name: 'ponderacion', label: 'Ponderación', type: 'number' }, { name: 'idarea', label: 'Área', type: 'select', source: SRC_SAE('areas', 'descripcion') }, { name: 'idasigcurs', label: 'Asignación', type: 'select', source: SRC_SAE('asignaciones', 'asignatura'), required: true }, { name: 'promedio', label: 'Promedio', type: 'number' }]),
    promedios: sae('Promedios generales', 'promedios',
        [{ header: 'PROMEDIO FINAL', key: 'promediofinal' }, { header: 'DESDE', key: 'gradodesde' }, { header: 'PARA', key: 'gradopara' }],
        [{ name: 'promediofinal', label: 'Promedio final', type: 'number', required: true }, { name: 'definitivo', label: 'Definitivo', type: 'boolean' }, { name: 'gradodesde', label: 'Grado desde', type: 'number' }, { name: 'gradopara', label: 'Grado para', type: 'number' }]),

    obsplan: sae('Plantilla observador', 'plan',
        [{ header: 'TÍTULO', key: 'titulo' }],
        [{ name: 'idinstitucion', label: 'Institución', type: 'select', source: SRC_INST, required: true }, { name: 'titulo', label: 'Título', type: 'text' }, { name: 'parrafo1', label: 'Párrafo 1', type: 'textarea' }, { name: 'parrafo2', label: 'Párrafo 2', type: 'textarea' }]),
    obsresponsabilidades: sae('Grupos de responsabilidad', 'responsabilidades',
        [{ header: 'NOMBRE', key: 'nombre' }, { header: 'DESCRIPCIÓN', key: 'descripcion' }],
        [{ name: 'idinstitucion', label: 'Institución', type: 'select', source: SRC_INST, required: true }, { name: 'nombre', label: 'Nombre', type: 'text', required: true }, { name: 'descripcion', label: 'Descripción', type: 'textarea' }]),
    obssubresponsabilidades: sae('Responsabilidades', 'subresponsabilidades',
        [{ header: 'NOMBRE', key: 'nombre' }, { header: 'DESCRIPCIÓN', key: 'descripcion' }],
        [{ name: 'idresponsabilidad', label: 'Grupo', type: 'select', source: SRC_SAE('responsabilidades', 'nombre'), required: true }, { name: 'nombre', label: 'Nombre', type: 'text', required: true }, { name: 'descripcion', label: 'Descripción', type: 'textarea' }]),
    obsobservaciones: sae('Observaciones', 'observaciones',
        [{ header: 'ESTUDIANTE', key: 'estudiante' }, { header: 'DESCRIPCIÓN', key: 'descripcion' }, { header: 'FECHA', key: 'fecha' }],
        [{ name: 'idresponsabilidad', label: 'Grupo', type: 'select', source: SRC_SAE('responsabilidades', 'nombre'), required: true }, { name: 'idperiodo', label: 'Periodo', type: 'select', source: SRC_SAE('anolperi', 'descripcion') }, { name: 'idmatricula', label: 'Matrícula', type: 'select', source: SRC_SAE('matriculas', 'estudiante'), required: true }, { name: 'descripcion', label: 'Descripción', type: 'textarea', required: true }, { name: 'fecha', label: 'Fecha', type: 'date' }]),
    obsevaluaciones: sae('Evaluación del observador', 'evaluaciones',
        [{ header: 'RESPONSABILIDAD', key: 'responsabilidad' }, { header: 'FECHA', key: 'fecha' }],
        [{ name: 'idperiodo', label: 'Periodo', type: 'select', source: SRC_SAE('anolperi', 'descripcion') }, { name: 'idmatricula', label: 'Matrícula', type: 'select', source: SRC_SAE('matriculas', 'estudiante'), required: true }, { name: 'idresponsabilidad', label: 'Responsabilidad', type: 'select', source: SRC_SAE('subresponsabilidades', 'nombre'), required: true }, { name: 'idcriterio', label: 'Criterio', type: 'number', required: true }, { name: 'fecha', label: 'Fecha', type: 'date' }]),

    usuarios: sae('Usuarios SAE', 'usuarios',
        [{ header: 'NICK', key: 'nick' }, { header: 'NOMBRE', key: 'nombre' }, { header: 'ROL', key: 'rol' }],
        [{ name: 'nombre', label: 'Nombre', type: 'text' }, { name: 'nick', label: 'Usuario', type: 'text', required: true }, { name: 'clave', label: 'Clave', type: 'text', required: true }, { name: 'idrol', label: 'Rol', type: 'select', source: SRC_SAE('roles', 'nombre') }]),
    roles: sae('Roles SAE', 'roles',
        [{ header: 'NOMBRE', key: 'nombre' }, { header: 'DESCRIPCIÓN', key: 'descripcion' }],
        [{ name: 'nombre', label: 'Nombre', type: 'text', required: true }, { name: 'descripcion', label: 'Descripción', type: 'text' }, { name: 'paginaentrada', label: 'Página de entrada', type: 'text' }]),
    menus: sae('Menús SAE', 'menus',
        [{ header: 'NOMBRE', key: 'nombre' }, { header: 'ORDEN', key: 'orden' }],
        [{ name: 'nombre', label: 'Nombre', type: 'text', required: true }, { name: 'descripcion', label: 'Descripción', type: 'text' }, { name: 'destino', label: 'Destino', type: 'text' }, { name: 'orden', label: 'Orden', type: 'number' }]),
    opciones: sae('Opciones de menú SAE', 'opciones',
        [{ header: 'NOMBRE', key: 'nombre' }, { header: 'ENLACE', key: 'enlace' }, { header: 'MENÚ', key: 'menu' }],
        [{ name: 'idmenu', label: 'Menú', type: 'select', source: SRC_SAE('menus', 'nombre'), required: true }, { name: 'nombre', label: 'Nombre', type: 'text', required: true }, { name: 'descripcion', label: 'Descripción', type: 'text' }, { name: 'enlace', label: 'Enlace', type: 'text' }, { name: 'icono', label: 'Icono', type: 'text' }, { name: 'orden', label: 'Orden', type: 'number' }]),
    privilegiosrol: sae('Privilegios por rol', 'privilegiosrol',
        [{ header: 'ROL', key: 'idrol' }, { header: 'OPCIÓN', key: 'idopcion' }],
        [{ name: 'idrol', label: 'Rol', type: 'select', source: SRC_SAE('roles', 'nombre'), required: true }, { name: 'idopcion', label: 'Opción', type: 'select', source: SRC_SAE('opciones', 'nombre'), required: true }]),
    privilegiosusuario: sae('Privilegios por usuario', 'privilegiosusuario',
        [{ header: 'USUARIO', key: 'idusuario' }, { header: 'OPCIÓN', key: 'idopcion' }],
        [{ name: 'idusuario', label: 'Usuario', type: 'select', source: SRC_SAE('usuarios', 'nick'), required: true }, { name: 'idopcion', label: 'Opción', type: 'select', source: SRC_SAE('opciones', 'nombre'), required: true }]),
    uniones: sae('Enlace usuario-académico', 'uniones',
        [{ header: 'USUARIO', key: 'idusuario' }, { header: 'ACADÉMICO', key: 'idacademico' }],
        [{ name: 'idusuario', label: 'Usuario', type: 'select', source: SRC_SAE('usuarios', 'nick'), required: true }, { name: 'idacademico', label: 'ID académico', type: 'text', required: true }]),

    // ================= PREESCOLAR (esquema preescolar) =================
    ambitos: pre('Ámbitos de preescolar', 'ambitos',
        [{ header: 'CÓDIGO', key: 'codigo', width: '100px' }, { header: 'DESCRIPCIÓN', key: 'descripcion' }],
        [{ name: 'codigo', label: 'Código', type: 'text' }, { name: 'descripcion', label: 'Descripción', type: 'text', required: true }, { name: 'comentario', label: 'Comentario', type: 'textarea' }]),
    dimensiones: pre('Dimensiones de preescolar', 'dimensiones',
        [{ header: 'CÓDIGO', key: 'codigo', width: '100px' }, { header: 'DESCRIPCIÓN', key: 'descripcion' }, { header: 'ABREV.', key: 'abreviatura', width: '90px' }],
        [{ name: 'codigo', label: 'Código', type: 'text' }, { name: 'descripcion', label: 'Descripción', type: 'text', required: true }, { name: 'comentario', label: 'Comentario', type: 'textarea' }, { name: 'abreviatura', label: 'Abreviatura', type: 'text' }]),
    preasignaciones: pre('Asignaciones de preescolar', 'asignaciones',
        [{ header: 'ÁMBITO', key: 'ambito' }, { header: 'DIMENSIÓN', key: 'dimension' }, { header: 'CURSO', key: 'curso' }, { header: 'DOCENTE', key: 'docente' }],
        [{ name: 'idambito', label: 'Ámbito', type: 'select', source: SRC_PRE('ambitos', 'descripcion'), required: true, get: 'idambito' }, { name: 'iddimension', label: 'Dimensión', type: 'select', source: SRC_PRE('dimensiones', 'descripcion'), required: true, get: 'iddimension' }, { name: 'idcurso', label: 'Curso', type: 'select', source: SRC_SAE('cursos', 'nombre'), required: true, get: 'idcurso' }, { name: 'iddocente', label: 'Docente', type: 'select', source: { tipo: 'sae', recurso: 'docentes', label: DOCENTE_LABEL }, required: true, get: 'iddocente' }, { name: 'duracion', label: 'Duración', type: 'number' }]),
    prenotas: pre('Notas de preescolar', 'notas',
        [{ header: 'ESTUDIANTE', key: 'estudiante' }, { header: 'VALOR', key: 'valor' }, { header: 'FECHA', key: 'fecha' }],
        [{ name: 'idasignacion', label: 'Asignación', type: 'select', source: SRC_PRE('asignaciones', 'dimension'), required: true, get: 'idasignacion' }, { name: 'idcompetencia', label: 'Competencia', type: 'select', source: SRC_SAE('competencias', 'descripcion'), get: 'idcompetencia' }, { name: 'idperiodo', label: 'Periodo', type: 'select', source: SRC_SAE('anolperi', 'descripcion'), get: 'idperiodo' }, { name: 'idmatricula', label: 'Matrícula', type: 'select', source: SRC_SAE('matriculas', 'estudiante'), required: true, get: 'idmatricula' }, { name: 'valor', label: 'Valor', type: 'number', required: true }, { name: 'fecha', label: 'Fecha', type: 'date' }, { name: 'observacion', label: 'Observación', type: 'textarea' }]),
    prenovedades: pre('Novedades de preescolar', 'novedades',
        [{ header: 'ESTUDIANTE', key: 'estudiante' }, { header: 'TIPO', key: 'tiponovedad' }, { header: 'FECHA', key: 'fecha' }],
        [{ name: 'idasignacion', label: 'Asignación', type: 'select', source: SRC_PRE('asignaciones', 'dimension'), required: true, get: 'idasignacion' }, { name: 'idperiodo', label: 'Periodo', type: 'select', source: SRC_SAE('anolperi', 'descripcion'), get: 'idperiodo' }, { name: 'idmatricula', label: 'Matrícula', type: 'select', source: SRC_SAE('matriculas', 'estudiante'), required: true, get: 'idmatricula' }, { name: 'idtiponovedad', label: 'Tipo de novedad', type: 'select', source: SRC_CAT('tiposnovedad', 'ctiponovedesc'), required: true, get: 'idtiponovedad' }, { name: 'fecha', label: 'Fecha', type: 'date' }, { name: 'observacion', label: 'Observación', type: 'textarea' }]),
};

export default CRUD;
